### ISSUE TITLE
How can I run the application?

### ISSUE THREAD

**Issue by iamouttacontrol** [loris2222/stop_webex_flash#1]
Hey loris,
first, thanks for your effort for writing such a program to disable the flashing icon. And yes fuck you WebEx :). 
I have less experience in github and don't know how to "run" your program because it isn't an .exe file? Should I copy the file stopwebexflash.au3 into the WebEx file or what exactly have I should do? 
Keep up,
an upcoming computer-scienticst 👍

**Comment by loris2222** [comment]
Hi, you can run the program by either compiling the code using the AutoIT toolkit, or more simply by downloading the .exe from the release section in the repository. You can find it in the right sidebar in the repo page. Let me know if you find it!
